CREATE DATABASE IF NOT EXISTS db_pw2;
USE db_pw2;

CREATE TABLE login (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuario VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL
);

CREATE TABLE usuario (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(80) NOT NULL,
    email VARCHAR(100) NOT NULL,
    idade VARCHAR(40),
    id_login INT NOT NULL,
    FOREIGN KEY (id_login) REFERENCES login(id) ON DELETE CASCADE
);


CREATE TABLE produto (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(80) NOT NULL,
    valor VARCHAR(40) NOT NULL,
    marca VARCHAR(40)
);

ALTER TABLE produto ADD COLUMN preco DOUBLE NOT NULL;
ALTER TABLE produto ADD COLUMN descricao VARCHAR(255) NOT NULL;
ALTER TABLE produto ADD COLUMN quantidade DOUBLE NOT NULL;
ALTER TABLE produto ADD COLUMN categoria VARCHAR(255) NOT NULL;
ALTER TABLE produto ADD COLUMN caminho_do_produto VARCHAR(255) NOT NULL;
ALTER TABLE produto ADD COLUMN data_cadastro DATE NOT NULL;
ALTER TABLE produto ADD COLUMN ativo BOOLEAN NOT NULL;
